pipeline {
  agent any
  environment {
    UNITY = '"C:\\Program Files\\Unity\\Hub\\Editor\\2018.4.14f1\\Editor\\Unity.exe"'
    PROJECT = 'ContinuousIntegration'
    PLATFORM = 'StandaloneWindows64'
    OUTPUT = 'Build/ContinuousIntegration.exe'
  }
  stages {
    stage('Import Assets') {
      steps {
        bat "$UNITY -batchmode -quit -logFile - -projectPath $PROJECT -targetPlatform $PLATFORM -accept-apiupdate"
      }
    }
    stage('Check Shaders') {
      steps {
        bat "$UNITY -batchmode -quit -logFile - -projectPath $PROJECT -targetPlatform $PLATFORM -diag-debug-shader-compiler"
      }
    }
    stage('Refresh Database') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath $PROJECT -targetPlatform $PLATFORM -executeMethod UnityEditor.AssetDatabase.Refresh"
      }
    }
    stage('Run Unit Tests') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath $PROJECT -targetPlatform $PLATFORM -runEditorTests"
      }
    }
    stage('Build Player') {
      steps {
        bat "$UNITY -batchmode -logFile - -projectPath $PROJECT -targetPlatform $PLATFORM -buildWindows64Player $OUTPUT"
      }
    }
  }
}